### ISSUE TITLE
Constants in the gen_lmbd.py script

### ISSUE THREAD

**Issue by dardanbekteshi** [yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks#2]
Hi,

I am trying to understand and run the gen_lmbd.py script. There are some constants defined in the gen_lmbd.py file, for which I am not sure what they mean. In particular: 

https://github.com/yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks/blob/5dd96c423eaea7ae94d9f8b3a341e1e009001d29/caffe-plier/gen_lmdb.py#L13-L16

- MAX_HEIGHT
I think this needs to be set much higher, since it refers to the max number of nodes/triangles of a given mesh?

- WIDTH
Why is this set to 4?

- CHANNEL
the documentation says it is the feature number. I am wondering, if I only train for spin images, for example, would I need to set it up to 100 instead of 600?

- conv_size
https://github.com/yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks/blob/5dd96c423eaea7ae94d9f8b3a341e1e009001d29/caffe-plier/gen_lmdb.py#L87

I guess need to set this to [10,10,10,10,10] if 9 neighbors are chosen for the Breadth First Search?

Ping @yuangan 😄

**Comment by dardanbekteshi** [comment]
Update: 
I realized that the CHANNELS constant gets overridden to the correct number in the last loop:
https://github.com/yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks/blob/5dd96c423eaea7ae94d9f8b3a341e1e009001d29/caffe-plier/gen_lmdb.py#L225

**Comment by yuangan** [comment]
MAX_HEIGHT = 5 
 WIDTH = 4 
It's used to make sure the memory is enough. But as the experiment goes, we find it hard to make sure the largest memory that it should be allocated because the number of meshes is unsure. So we added 
zeros after 100000000, when the memory is not enough.
https://github.com/yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks/blob/5dd96c423eaea7ae94d9f8b3a341e1e009001d29/caffe-plier/gen_lmdb.py#L54-L55
But don't worry, the generated dataset won't consume more hard disk memory than it should be. So you don't need to worry about it, just run and you'll get lmdb dataset if there is nothing wrong.

**Comment by dardanbekteshi** [comment]
@yuangan thanks for the clarification about the first constants.
What about the question regarding the conv list?

 - conv_size
https://github.com/yuangan/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks/blob/5dd96c423eaea7ae94d9f8b3a341e1e009001d29/caffe-plier/gen_lmdb.py#L87

**I guess need to set this to [10,10,10,10,10]** if 9 neighbors are chosen for the Breadth First Search?
https://github.com/dardanbekteshi/3D-Shape-Segmentation-via-Shape-Fully-Convolutional-Networks/blob/36bff343763aa73365df4839587897ad32cb0457/preprocessing/pool/start_combine.py#L15

**Comment by dardanbekteshi** [comment]
I just realized that conv_size is used similarly as the MAX_HEIGHT and WIDTH you explained in the previous comment 😅.
